spring:
 profiles:
  active: test
server:
 port: 8081
 servlet:
  context-path: /comments-service
app:
 logging:
  enabled: true
 exceptions:
  handler:
   enabled: true
logging:
 file:
  path: ./logs/comments-service.log