version: '3.9'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: ${REDIS_PORT}
    ports:
      - ${POSTGRES_HOST_PORT:-5435}:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - net
  redis:
    image: redis:8.0-M02-alpine
    restart: always
    ports:
      - ${REDIS_HOST_PORT:-6379}:6379
    volumes:
      - cache:/data

  news-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres-db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/news
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - net


networks:
  net:
    driver: bridge

volumes:
  db:
    driver: local
  cache:
    driver: local